version: '3.7'

services:
  minecraft:
    image: felixklauke/paperspigot:1.16.1
    container_name: minecraft
    stdin_open: true
    tty: true
    restart: always
    environment:
      - SHELL=/bin/bash
    networks:
      - minecraft
    ports:
      - 25565:25565
    volumes:
      - server:/opt/minecraft
  db:
    container_name: minecraft-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minecraft_267223
      MYSQL_HOST: localhost
    networks:
      - minecraft
    volumes: 
     - db:/var/lib/minecraftdb
volumes:
  server: {}
  db: {}

networks:
  minecraft: {}
