version: '3.7'

services:
  minecraft:
    image: felixklauke/paperspigot:1.16.1
    container_name: minecraft
    stdin_open: true
    tty: true
    restart: always
    networks:
      - minecraft
    ports:
      - 25565:25565
    volumes:
      - config:/opt/minecraft/config
      - worlds:/opt/minecraft/worlds
      - plugins:/opt/minecraft/plugins
      - data:/opt/minecraft/data
      - logs:/opt/minecraft/logs

  db:
    image: mariadb
    container_name: minecraft-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minecraft
      MYSQL_HOST: localhost
    networks:
      - minecraft
    volumes: 
     - db:/var/lib/mysql

volumes:
  config: {}
  worlds: {}
  plugins: {}
  data: {}
  logs: {}
  db: {}

networks:
  minecraft: {}
